export const USERCHECK_REQUEST_POST = 'USERCHECK_REQUEST_POST'
export const USERCHECK_RECEIVED='USERCHECK_RECEIVED'
export const USERCHECK_ANSWER='USERCHECK_ANSWER'
export const USERCHECK_ERROR='USERCHECK_ERROR'
